version: "3"
services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    entrypoint: ["yarn", "develop"]
    environment:
      - GATSBY_TELEMETRY_DISABLED=1
